SeatYourself/config/routes.rb
Rails.application.routes.draw do

	root 'restaurants#index'

	resources :sessions, only: [:new, :create, :destroy]

	resources :restaurants do
		resources :reviews, only: [:show, :create, :destroy]
		resources :reservations
	end

	resources :users

end

SeatYourself/app/models/reservation.rb
class Reservation < ActiveRecord::Base

  belongs_to :restaurant
  belongs_to :user

  validates :date, :time, presence: true
  validates :party_size, numericality: {only_integer: true}

  validate :valid_date_range, :future_date_only
  validate :available_seats
  validate :reserved_seats
  validate :availability
  validate :hours_of_operation

  def valid_date_range
    if !date.blank? && date > Date.today + 30.days
      errors.add(:date, "for bookings can only be made 30 days in advance.")
    end
  end

  def future_date_only
    if !date.blank? && date <= Date.today
      errors.add(:date, "for bookings can only be made for a later date.")
    end
  end

  def available_seats
    self.restaurant_seats - reserved_seats
  end

  def restaurant_seats
    if self.restaurant
      restaurant.seats
    else
      0
    end
  end

  def reserved_seats
    if time && restaurant
      Reservation.where(time: time.beginning_of_hour..time.end_of_hour, restaurant_id: restaurant.id).sum(:party_size)
    else
      0
    end
  end

  def availability
    v_party_size = party_size.blank? ? 0 : party_size
    if v_party_size != 0 && ((reserved_seats + v_party_size) > available_seats)
      errors.add(:party_size, "too large, there are no available bookings.")
    end
  end

  def hours_of_operation
    if !time.blank? && !time.between?(restaurant.opening, restaurant.closing)
      errors.add(:time, "for reservation not available! Boo.")
    end
  end

end

SeatYourself/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  validates :name, :opening, :closing, :address, :phone, presence: true
  validates :seats, numericality: {only_integer: true}

  has_many :reservations
  has_many :reviews
  has_many :users, through: :reservations

end

SeatYourself/app/models/review.rb
class Review < ActiveRecord::Base
  validates :comment, presence: true

  belongs_to :restaurant
  belongs_to :user
end

SeatYourself/app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  validates :first_name, :last_name, :phone, :password, presence: true
  validates :email, uniqueness: true

  has_many :reservations
  has_many :reviews
  has_many :restaurants, through: :reservations

end

SeatYourself/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

end

SeatYourself/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

SeatYourself/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :load_restaurant
  before_action :ensure_logged_in

  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user = current_user


      if @reservation.save
        redirect_to root_url, notice: "Reservation created successfully!"
      else
        render 'new'
      end

  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])

    if @reservation.update_attributes(reservation_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end


  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to root_url
  end

  private
  def reservation_params
    params.require(:reservation).permit(:date, :time, :party_size, :comment)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

SeatYourself/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    if current_user
      @reservation = @restaurant.reservations.build
    end

    if current_user
      @review = @restaurant.reviews.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_url
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_url(@restaurant)
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_url
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :opening, :closing, :seats)
  end
end

SeatYourself/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :load_restaurant
  before_action :ensure_logged_in, only: [:create, :destroy]

  def create
    @review = @restaurant.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to restaurant_url(@restaurant), notice: 'Review created successfully'
    else
      redirect_to restaurant_url(@restaurant), notice: 'Review could not be added.'
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

SeatYourself/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

SeatYourself/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_path, notice: "Signed up!"
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    unless current_user == @user
      flash[:notice] = "Wrong ID"
      redirect_to root_url
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      render 'edit'
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone, :email, :password, :password_confirmation)
  end
end

SeatYourself/app/helpers/application_helper.rb
module ApplicationHelper
end

SeatYourself/app/helpers/home_helper.rb
module HomeHelper
end

SeatYourself/app/helpers/reservations_helper.rb
module ReservationsHelper
end

SeatYourself/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

SeatYourself/app/helpers/reviews_helper.rb
module ReviewsHelper
end

SeatYourself/app/helpers/sessions_helper.rb
module SessionsHelper
end

SeatYourself/app/helpers/users_helper.rb
module UsersHelper
end

SeatYourself/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>
<nav>
  <nav class="nav-bar">
    <p class="userinfo">
      <ul>
        <li class="username"><% if current_user %>
        Signed in as <%= link_to current_user.first_name, edit_user_path(current_user) %>.</li>
        <li class="main"><%= link_to "Main page", root_path %></li>
        <li class="logs"><%= link_to "Log out", session_path("current"), :method => :delete %></li>
        <% else %>
          <li class="logs"><%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </p>
  </nav>
</nav>

  <%= yield %>

</body>
<footer>
<p class="footer-text">Copyright VCKEH 2016</p>
</footer>
</html>

SeatYourself/app/views/reservations/_form.html.erb
<%= form_for ([@restaurant, @reservation]) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_field :time %>
  </div>

  <div class="field">
    <%= f.label :party_size %><br>
    <%= f.number_field :party_size %>
  </div>

  <div class="field">
    <%= f.label :comment, :value => "Comments (Optional)" %><br>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

SeatYourself/app/views/reservations/edit.html.erb
<%= render "form" %>

<%= link_to "Back to Restaurant", restaurant_path(@restaurant) %>

SeatYourself/app/views/reservations/new.html.erb
<h1>Make a Reservation</h1>

<%= render 'form' %>

SeatYourself/app/views/restaurants/_form.html.erb
<%= form_for (@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :opening %><br>
    <%= f.time_field :opening%>
  </div>

  <div class="field">
    <%= f.label :closing %><br>
    <%= f.time_field :closing %>
  </div>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :url, value: "Restaurant Photo URL" %><br>
    <%= f.text_field :url %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

SeatYourself/app/views/restaurants/index.html.erb
<div class="homepage">
  <div class="main-title">
    <h1>Welcome to SeatYourself</h1>
  </div>
  <div class="rest-list">
    <% @restaurants.each do |restaurant| %>
    <ul>
      <button>
        <li>
          <%= link_to restaurant.name, restaurant_path(restaurant) %>
        </li>
      </button>
    </ul>
  <% end %>
  </div>

  <div class="about-us">

  </div>
</div>

SeatYourself/app/views/restaurants/new.html.erb
<h1>Add a Restaurant</h1>

<%= render 'form' %>

SeatYourself/app/views/restaurants/show.html.erb
<div class="show-page">
  <h1><%= @restaurant.name %></h1>
    <p><img src ="<%= @restaurant.url %>"></p>
    <p><%= link_to "Make a Reservation", new_restaurant_reservation_path(@restaurant) %></p>
  <br>
  <h2>Reviews</h2>
    <p>
      <% @restaurant.reviews.each do |review| %>
      <%= review.comment %>
      <br>
        <% if review.user != nil %>
          <em> by <%= review.user.first_name %></em>
          Added on: <%= review.created_at %>
        <% end %>
      <% end %>
    </p>

    <% if current_user %>
      <h4>New Review</h4>
      <%= form_for([@restaurant, @review]) do |f| %>
        <% if @review.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
              <ul>
              <% @review.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
          </div>
        <% end %>

      <div class="field">
        <%= f.label :comment %><br />
        <%= f.text_area :comment %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
      <% end %>
    <% else %>
      <p>Please <%= link_to "Log in", new_session_path %> to add a review.</p>
    <% end %>
</div>

SeatYourself/app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

SeatYourself/app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

SeatYourself/app/views/users/_form.html.erb
<%= form_for (@user) do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2> Could not save User, the following fields cannot be blank:</h2>

			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :first_name %><br>
		<%= f.text_field :first_name %>
	</div>

	<div class="field">
		<%= f.label :last_name %><br>
		<%= f.text_field :last_name %>
	</div>

	<div class="field">
		<%= f.label :email %><br>
		<%= f.email_field :email %>
	</div>

	<div class="field">
		<%= f.label :phone %><br>
		<%= f.text_field :phone %>
	</div>

	<div class="field">
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

SeatYourself/app/views/users/edit.html.erb
<%= render "form" %>

SeatYourself/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

SeatYourself/app/views/users/show.html.erb
<p>Hello <%= current_user.first_name %></p>